./simusched ejercicio7.tsk 1 SchedRR 1 | java SchedRRTest > result.out
./simusched ejercicio7.tsk 1 SchedRR 2 | java SchedRRTest >> result.out
./simusched ejercicio7.tsk 1 SchedRR 3 | java SchedRRTest >> result.out
./simusched ejercicio7.tsk 1 SchedRR 4 | java SchedRRTest >> result.out
./simusched ejercicio7.tsk 1 SchedRR 5 | java SchedRRTest >> result.out
./simusched ejercicio7.tsk 1 SchedRR 6 | java SchedRRTest >> result.out
./simusched ejercicio7.tsk 1 SchedRR 7 | java SchedRRTest >> result.out
./simusched ejercicio7.tsk 1 SchedRR 8 | java SchedRRTest >> result.out
./simusched ejercicio7.tsk 1 SchedRR 9 | java SchedRRTest >> result.out
./simusched ejercicio7.tsk 1 SchedRR 10 | java SchedRRTest >> result.out
./simusched ejercicio7.tsk 1 SchedRR 11 | java SchedRRTest >> result.out
./simusched ejercicio7.tsk 1 SchedRR 12 | java SchedRRTest >> result.out
./simusched ejercicio7.tsk 1 SchedRR 13 | java SchedRRTest >> result.out
./simusched ejercicio7.tsk 1 SchedRR 14 | java SchedRRTest >> result.out
./simusched ejercicio7.tsk 1 SchedRR 15 | java SchedRRTest >> result.out
./simusched ejercicio7.tsk 1 SchedRR 16 | java SchedRRTest >> result.out
./simusched ejercicio7.tsk 1 SchedRR 17 | java SchedRRTest >> result.out
./simusched ejercicio7.tsk 1 SchedRR 18 | java SchedRRTest >> result.out
./simusched ejercicio7.tsk 1 SchedRR 19 | java SchedRRTest >> result.out
./simusched ejercicio7.tsk 1 SchedRR 20 | java SchedRRTest >> result.out
./simusched ejercicio7.tsk 1 SchedRR 21 | java SchedRRTest >> result.out
./simusched ejercicio7.tsk 1 SchedRR 22 | java SchedRRTest >> result.out
./simusched ejercicio7.tsk 1 SchedRR 23 | java SchedRRTest >> result.out
./simusched ejercicio7.tsk 1 SchedRR 24 | java SchedRRTest >> result.out
./simusched ejercicio7.tsk 1 SchedRR 25 | java SchedRRTest >> result.out
./simusched ejercicio7.tsk 1 SchedRR 26 | java SchedRRTest >> result.out
./simusched ejercicio7.tsk 1 SchedRR 27 | java SchedRRTest >> result.out
./simusched ejercicio7.tsk 1 SchedRR 28 | java SchedRRTest >> result.out
./simusched ejercicio7.tsk 1 SchedRR 29 | java SchedRRTest >> result.out
./simusched ejercicio7.tsk 1 SchedRR 30 | java SchedRRTest >> result.out
